name: MacOS ton_crypto_lib build (portable, arm64, debug)

on: [push,workflow_dispatch,workflow_call]

jobs:
  build:
    runs-on: macos-14

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - uses: cachix/install-nix-action@v23
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}

      - name: Build TON
        run: |
          cp assembly/nix/build-toncryptolib-macos-nix-debug.sh .
          chmod +x build-toncryptolib-macos-nix-debug.sh
          ./build-toncryptolib-macos-nix-debug.sh -t

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        with:
          name: ton_crypto_lib-arm64-macos-debug
          path: artifacts
